spring:
  application:
    name: user-management-server
  config:
    import: optional:configserver:http://localhost:8888

# define postgres database connection
#spring.datasource.url=jdbc:postgresql://localhost:3000/user-management
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

